# LICENSE

import os, sys, time, pathlib, shutil
from os.path import join, exists
from shutil import copyfile, rmtree
from platformio import proc

VER = '0.0.0'
ver = {'PICO_SDK_VERSION_MAJOR':'0', 'PICO_SDK_VERSION_MINOR':'0', 'PICO_SDK_VERSION_REVISION':'0' }

def INFO(str): 
    print('[INSTALL]', str)

def ERROR(txt):
    print('❖ ERROR ❖ [INSTALL]', txt)
    exit(-1)

def MKDIR(dir):
    if not exists( dir ): 
        if not os.path.isdir( dir ):
            try: 
                os.mkdir(dir)
                return False # done
            except OSError:
                ERROR ("Creation of the directory %s failed" % dir)
        else:
            ERROR ("Dir is not dir %s" % dir)
    return True # exists

###############################################################################

def get_ver(item, key):
    if key in item: 
        x = item.find(' ')
        y = item.find(')')
        if x > -1 and y > -1:
            ver[key] = item[ x + 1 : y]

def get_pico_sdk_version( pico_dir ):
    global VER
    f = open( join( pico_dir, 'pico_sdk_version.cmake' ) )
    text = f.read()
    f.close()    
    text = text.strip().split('\n')
    for item in text:
        if False == item.startswith('set(') or item.find(')') == -1 or item.find('$') > -1: continue
        get_ver(item, 'PICO_SDK_VERSION_MAJOR')
        get_ver(item, 'PICO_SDK_VERSION_MINOR')
        get_ver(item, 'PICO_SDK_VERSION_REVISION')
    VER = '%s.%s.%s' % ( ver['PICO_SDK_VERSION_MAJOR'], ver['PICO_SDK_VERSION_MINOR'], ver['PICO_SDK_VERSION_REVISION'] ) 
    return VER     

###############################################################################

def create_folder_gcc( platformio_dir ):
    gcc_dir = join( platformio_dir, 'gcc' )
    if MKDIR( gcc_dir ): return
    f = open( join( gcc_dir, 'gcc-syscall.c' ), 'w' )
    f.write(
'''
#include <sys/stat.h>
extern int __attribute__((weak)) _fstat(int file, struct stat *st){ st->st_mode = S_IFCHR; return 0; }
extern int __attribute__((weak)) _close(int file) { return -1; }
extern int __attribute__((weak)) _isatty(int file) { return 1; }
extern int __attribute__((weak)) _lseek(int file, int ptr, int dir) { return 0; }
extern int __attribute__((weak)) _read(int handle, char *buffer, int length) { return -1; }
extern int __attribute__((weak)) _write(int handle, char *buffer, int length) { return -1; }
'''        
    )
    f.close()

def create_folder_inc( pico_dir, platformio_dir ):
    global VER
    pico_src_dir = join( pico_dir, 'src' )
    inc_dir = join( platformio_dir, 'inc' )
    if MKDIR( inc_dir ): return
    for root, dirs, files in os.walk( pico_src_dir ):
        if 'host' in root: continue
        if 'include' not in root: continue       
        name = root[ root.index('include') + 8:] # name after include
        MKDIR( join( inc_dir, name ) )
        for file in files:
            ext = pathlib.Path(file).suffix
            if ext == '.h' or ext == '.S':
                src_file = join(root, file)
                dst_file = join(inc_dir, name, file)
                if False == exists( dst_file ): 
                    copyfile( src_file, dst_file )
                else: 
                    ERROR('INCLUDE FILE EXISTS: %s' % dst_file)

        f = open( join(platformio_dir, 'version'), 'w' )
        f.write(VER)
        f.close()

###############################################################################

# TODO check dst folder
def create_config_autogen( pico_dir ):
    filename = join( pico_dir, 'src', 'rp2_common', 'pico_platform', 'include', 'pico', 'config_autogen.h' )
    if not exists( filename ): 
        f = open( filename, 'w' ) 
        f.write('// config autogen: PlatformIO')
        f.close()

# TODO check dst folder
def create_version( pico_dir ):
    global VER
    filename = join( pico_dir, 'src', 'rp2_common', 'pico_platform', 'include', 'pico', 'version.h')
    if not exists( filename ): 
        f = open( filename, 'w' ) 
        f.write(
'''
/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * 
 * PlatformIO - WizIO
 * https://github.com/
 */

// ---------------------------------------
// THIS FILE IS AUTOGENERATED; DO NOT EDIT
// ---------------------------------------

#ifndef _PICO_VERSION_H
#define _PICO_VERSION_H

#define PICO_SDK_VERSION_MAJOR      %s
#define PICO_SDK_VERSION_MINOR      %s
#define PICO_SDK_VERSION_REVISION   %s
#define PICO_SDK_VERSION_STRING     "%s < PlatformIO >"

#endif
''' % ( ver['PICO_SDK_VERSION_MAJOR'], ver['PICO_SDK_VERSION_MINOR'], ver['PICO_SDK_VERSION_REVISION'],  VER ) )
        f.close()

###############################################################################

def create_patch( pico_dir ):
    get_pico_sdk_version( pico_dir )

    platformio_dir = join( pico_dir, 'platformio' )

    version_file = join(platformio_dir, 'version') 
    if exists( version_file ): 
        f = open( version_file, 'r' ); v = f.read(); f.close();
        if v != VER:
            print('Update current version < %s > to < %s >' % (v, VER) )
            shutil.rmtree(platformio_dir, ignore_errors=False)
            time.sleep(1)

    MKDIR( platformio_dir )  

    create_config_autogen(pico_dir)   
    create_version(pico_dir)    

    create_folder_gcc(platformio_dir) 
    create_folder_inc(pico_dir, platformio_dir)  

def dev_install( framework_dir ):
    global VER    

    if not exists( framework_dir ):  
        return 

    pico_dir = join( framework_dir, 'pico-sdk' )

    if exists( pico_dir ):  
        create_patch( pico_dir ) # if manual install/update
        return 

    ## CLONE BEGIN ##

    start_time = time.time()
    INFO('Clone pico-sdk ( less than a minute, Plese wait )')
    args = [ 'git', 'clone', 'https://github.com/raspberrypi/pico-sdk', pico_dir, '--quiet' ]
    res = proc.exec_command( args, stdout=sys.stdout, stderr=sys.stderr, stdin=sys.stdin )
    
    if 0 == res['returncode']: 
        INFO('Init submodules ...')
        args = ['git', 'submodule', 'init' , '--quiet' ]
        res = proc.exec_command( args, stdout=sys.stdout, stderr=sys.stderr, stdin=sys.stdin, cwd = pico_dir )

        if 0 == res['returncode']: 
            INFO('Updating submodules ...')
            args = ['git', 'submodule', 'update', pico_dir, '--quiet' ]
            res = proc.exec_command( args, stdout=sys.stdout, stderr=sys.stderr, stdin=sys.stdin, cwd = pico_dir )
           
    if 0 != res['returncode']:  
        rmtree(pico_dir, ignore_errors=False)
        ERROR('Result:%d ... Please, try later' % res)

    ## CLONE END   ##

    create_patch( pico_dir ) 

    INFO('PICO-SDK Version: %s' % VER )
    INFO('DONE ( %s sec )' % int( time.time() - start_time ) ) # DONE ( 24 sec )